spring:
  cloud:
    gateway:
      routes:
        - id: api-router
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
server:
  port: 8090
dubbo:
  application:
    # 设置应用的名称
    name: YunApi-backend-provider
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22223
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848
